# name of your application
APPLICATION = murata-dualstack-example-ns

# platform for which the application will be built
PLATFORM ?= octa

# Add shields used in application
# Murata
SHIELDS += Murata-dualstack
MURATA_CONNECTOR = 1
LORAWAN_APPLICATION = labProject
PRINT_FLOATS = 1

LOW_POWER = 1 #setting the code to low power \stm32l4xx
USE_BOOTLOADER = 1

# Path to the octa-stack base directory:
STACKBASE ?= ../..

include $(STACKBASE)/core/Makefile.core